### ISSUE TITLE
Page for collections

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant-web-ui#2]
Design a page, which should allow to view all existing collections in Qdrant

**Comment by Aankirz** [comment]
I want to work on this issue can you pls assign this to me

**Comment by monatis** [comment]
hi @Aankirz, if you intend to apply for GSoC, you are supposed to read [our guide](https://qdrant.to/gsoc23) and make an application at the GSoC website.

**Comment by KousikRoy-EC** [comment]
Hey can i work on this isssue?

**Comment by monatis** [comment]
@KousikRoy-EC please read my comment above. You are supposed to make an application at the GSoC website if your pursuing a GSoC internship. Read [here](https://qdrant.to/gsoc23).

**Comment by lekhit** [comment]
@generall design of a page like this is apperently similar to the navigation menu design
Here we need to take care of
1. Number of collections we are dealing with since that would decide the approch to how we shall be displaying the result.
2. here we also need to consider the fact that there is a possiblity of recursion 

- so we can choose page based design ie each layer is displayed on different page
advantage:
Each view will have clear and easy to access design making working on it simpler
disadvantage:
if someone is simply surfing on then changing between pages that to recursive pages is painfully difficult.

- we can go for Accordinated view based on MUI 
advantage:
this type of view will make the navigation a lot easier thus we can get a bird's eye view quick and crisp
disadvantage:
making multiple recursions on such a design will place restriction on the actual content size to be displayed.
if multiple views are needed (large number of collections) then we will need to focus on pagination again.

- we can make simple cards and drawer scheme
here loading for each drawer will depend on the backend ie how fast can it respond to the request.
assuming that we are building for local machine this is possibly the best idea

here are some of my views for this page please consider providing your opinion
