### ISSUE TITLE
Page for viewing collection content

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant-web-ui#3]
Desired features:

- Be able to see first N records of the collection
- Should be possible to click on records to see similar ones
- If payload contains links, try to render links as images
- Nested payload values render as json

**Comment by affan00733** [comment]
Hi ,
I am a working professional and willing to participate in GSOC 2023 so want to solve this issue

**Comment by KousikRoy-EC** [comment]
Hey can i work on this isssue?

**Comment by lekhit** [comment]
hey @generall 
since we are focusing on First N records 
1. we either need to keep N low or implement pagination/infinite scroll 

- in case of pagination the size of cards( as used in MUI ) need to fixed in which case this calls for provison of data from a side/lower panel (like Drawer from MUI)
- in case of infinite scroll we some how need to optimise on the fact that the display array on which we map values needs to be small enough to ensure smooth functioning for the page

2. click on record to find similar ones is easy task simply calls for a anchor tag/ button 
3. Rendering links as image is challenging I have used Nextjs where this kind of thing is handled by Lazy loading. However implementing this with react will be challenging. need help here
4. Rendering json is easy task because basically.

Who am I >[ Lekhit Borole](https://linkedin.com/in/lekhit) Web-developer with love for Machine-learning, expertise in React,Python.
My experience with a similar project where a machine learning model sends data and the data is rendered on website might be of interest to you. Presumable with this project a generic web-app can be built making the entire process simpler. Looking forward working with you.
here is the [link](https://bouk-lekhit.vercel.app/) for my previous project : https://bouk-lekhit.vercel.app 
it's a book recommendation system built to find book having similar content instead of relying on user based similarity used by most big firms. Built this when I need to find a similar book to [The Da VInci Code](https://www.amazon.in/Vinci-Code-Robert-Langdon/dp/0307474275).
![Screenshot 2023-03-13 at 1 06 35 PM](https://user-images.githubusercontent.com/82832791/224636330-9bfd591c-ce53-402e-ac6a-2d18332d1074.png)

Waiting to know your views 
Please consider working together. 
Thank you
